USE DATABASE DATAOPS_SOURCE;
USE SCHEMA OPENMETADATA;

CREATE OR REPLACE TABLE pipeline_runs (
    DB_NAME VARCHAR(256),
    SCHEMA_NAME VARCHAR(256),
    TABLE_NAME VARCHAR(256),
    EXPECTED_INSERTION_COUNT INTEGER,
    ACTUAL_INSERTION_COUNT INTEGER,
    IS_SUCCESS BOOLEAN,
    IS_FAILED BOOLEAN,
    IS_SKIPPED BOOLEAN,
    PIPELINE_RUN_TIMESTAMP TIMESTAMP_NTZ
)
